baseurl = "https://dataplayground.netlify.com"
theme = "cocoa-eh-hugo-theme"
builddrafts = false
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
#publishdir = "/public"
author = "Petr Schönbauer"
title = "Data playground"
disqusshortname = "dataplayground"
googleAnalytics = "UA-5171547-2"
pluralizelisttitles = false
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
disableKinds = ["taxonomy", "taxonomyTerm"]

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "blog"
copyright = "Copyright © 2019 Petr Schönbauer"
copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
logofile = "img/logo.png"
faviconfile = "img/logo.png"
highlightjs = true
# options for highlight.js (version, additional languages, and theme)
highlightjsVersion = "9.11.0"
highlightjsCDN = "https://cdn.bootcss.com"
highlightjsLang = ["r", "yaml"]
highlightjsTheme = "github"
progressively = true
latestpostcount = 5
email = "schonbauer.petr@gmail.com"
linkedin = "schonbauer-petr"
social_banner = "img/banner.png"
posts_navigation = true

